import {m} from "./packages/mithril/src/m.mjs"

const tags = [
    "a",
    "abbr",
    "acronym",
    "address",
    "applet",
    "area",
    "article",
    "aside",
    "audio",
    "b",
    "base",
    "basefont",
    "bdi",
    "bdo",
    "bgsound",
    "big",
    "blink",
    "blockquote",
    "body",
    "br",
    "button",
    "canvas",
    "caption",
    "center",
    "cite",
    "code",
    "col",
    "colgroup",
    "command",
    "content",
    "data",
    "datalist",
    "dd",
    "del",
    "details",
    "dfn",
    "dialog",
    "dir",
    "div",
    "dl",
    "dt",
    "element",
    "em",
    "embed",
    "fieldset",
    "figcaption",
    "figure",
    "font",
    "footer",
    "form",
    "frame",
    "frameset",
    "h1",
    "h2",
    "h3",
    "h4",
    "h5",
    "h6",
    "head",
    "header",
    "hgroup",
    "hr",
    "html",
    "i",
    "iframe",
    "image",
    "img",
    "input",
    "ins",
    "isindex",
    "kbd",
    "keygen",
    "label",
    "legend",
    "li",
    "link",
    "listing",
    "main",
    "map",
    "mark",
    "marquee",
    "math",
    "menu",
    "menuitem",
    "meta",
    "meter",
    "multicol",
    "nav",
    "nextid",
    "nobr",
    "noembed",
    "noframes",
    "noscript",
    "object",
    "ol",
    "optgroup",
    "option",
    "output",
    "p",
    "param",
    "picture",
    "plaintext",
    "pre",
    "progress",
    "q",
    "rb",
    "rbc",
    "rp",
    "rt",
    "rtc",
    "ruby",
    "s",
    "samp",
    "script",
    "section",
    "select",
    "shadow",
    "slot",
    "small",
    "source",
    "spacer",
    "span",
    "strike",
    "strong",
    "style",
    "sub",
    "summary",
    "sup",
    "svg",
    "table",
    "tbody",
    "td",
    "template",
    "textarea",
    "tfoot",
    "th",
    "thead",
    "time",
    "title",
    "tr",
    "track",
    "tt",
    "u",
    "ul",
    "var",
    "video",
    "wbr",
    "xmp"
]

const args = [
    [".test", "text"],
    ["#test", {key: "value"}, 1],
    [".test#test", "text"],
    ["#test.test", {key: "value"}, 1],
    [".test.test", "text"],
    ["#test#test", {key: "value"}, 1],
    ["[test]", "a", "b", "c"],
    [".test[test]", "a", "b", "c"],
    ["#test[test]", "a", "b", "c"],
    [".test.test[test]", "a", "b", "c"],
    [".test#test[test]", "a", "b", "c"],
    ["#test#test[test]", "a", "b", "c"],
    ["[test=1]", {key: "value"}, 1, 2, "3"],
    [".test[test=1]", {key: "value"}, 1, 2, "3"],
    ["#test[test=1]", {key: "value"}, 1, 2, "3"],
    [".test.test[test=1]", {key: "value"}, 1, 2, "3"],
    [".test#test[test=1]", {key: "value"}, 1, 2, "3"],
    ["#test#test[test=1]", {key: "value"}, 1, 2, "3"],
    ["[test=]", null, 1, 2, "3"],
    [".test[test=]", null, 1, 2, "3"],
    ["#test[test=]", null, 1, 2, "3"],
    [".test.test[test=]", null, 1, 2, "3"],
    [".test#test[test=]", null, 1, 2, "3"],
    ["#test#test[test=]", null, 1, 2, "3"],
    ["[test='1']", false, 1, 2, "3", {tag: "four", attrs: {key: "value", children: []}}],
    [".test[test='1']", false, 1, 2, "3", {tag: "four", attrs: {key: "value", children: []}}],
    ["#test[test='1']", false, 1, 2, "3", {tag: "four", attrs: {key: "value", children: []}}],
    [".test.test[test='1']", false, 1, 2, "3", {tag: "four", attrs: {key: "value", children: []}}],
    [".test#test[test='1']", false, 1, 2, "3", {tag: "four", attrs: {key: "value", children: []}}],
    ["#test#test[test='1']", false, 1, 2, "3", {tag: "four", attrs: {key: "value", children: []}}],
    ['[test="1"]', {tag: "one", attrs: {key: "value", children: []}}, "two", {three: "wat"}],
    ['.test[test="1"]', {tag: "one", attrs: {key: "value", children: []}}, "two", {three: "wat"}],
    ['#test[test="1"]', {tag: "one", attrs: {key: "value", children: []}}, "two", {three: "wat"}],
    ['.test.test[test="1"]', {tag: "one", attrs: {key: "value", children: []}}, "two", {three: "wat"}],
    ['.test#test[test="1"]', {tag: "one", attrs: {key: "value", children: []}}, "two", {three: "wat"}],
    ['#test#test[test="1"]', {tag: "one", attrs: {key: "value", children: []}}, "two", {three: "wat"}],
    ["[foo=1][bar][baz=][qux='1'].test", {key: "value"}, 1, 2, "3"],
]

const params = []

for (const tag of tags) {
    for (const [selector, ...rest] of args) {
        // Make sure the selector is flattened.
        params.push([tag.concat(selector), ...args])
    }
}

function loop() {
    for (const args of params) m(...args)
}

for (var i = 0; i < 1000; i++) loop()
